// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: language-agent/ApplicationRegisterService.proto
// Original file comments:
//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
#ifndef GRPC_language_2dagent_2fApplicationRegisterService_2eproto__INCLUDED
#define GRPC_language_2dagent_2fApplicationRegisterService_2eproto__INCLUDED

#include "language-agent/ApplicationRegisterService.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

// register service for ApplicationCode, this service is called when service starts.
class ApplicationRegisterService final {
 public:
  static constexpr char const* service_full_name() {
    return "ApplicationRegisterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status applicationCodeRegister(::grpc::ClientContext* context, const ::Application& request, ::ApplicationMapping* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationMapping>> AsyncapplicationCodeRegister(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationMapping>>(AsyncapplicationCodeRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationMapping>> PrepareAsyncapplicationCodeRegister(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationMapping>>(PrepareAsyncapplicationCodeRegisterRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void applicationCodeRegister(::grpc::ClientContext* context, const ::Application* request, ::ApplicationMapping* response, std::function<void(::grpc::Status)>) = 0;
      virtual void applicationCodeRegister(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ApplicationMapping* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationMapping>* AsyncapplicationCodeRegisterRaw(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ApplicationMapping>* PrepareAsyncapplicationCodeRegisterRaw(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status applicationCodeRegister(::grpc::ClientContext* context, const ::Application& request, ::ApplicationMapping* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ApplicationMapping>> AsyncapplicationCodeRegister(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ApplicationMapping>>(AsyncapplicationCodeRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ApplicationMapping>> PrepareAsyncapplicationCodeRegister(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ApplicationMapping>>(PrepareAsyncapplicationCodeRegisterRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void applicationCodeRegister(::grpc::ClientContext* context, const ::Application* request, ::ApplicationMapping* response, std::function<void(::grpc::Status)>) override;
      void applicationCodeRegister(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ApplicationMapping* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ApplicationMapping>* AsyncapplicationCodeRegisterRaw(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ApplicationMapping>* PrepareAsyncapplicationCodeRegisterRaw(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_applicationCodeRegister_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status applicationCodeRegister(::grpc::ServerContext* context, const ::Application* request, ::ApplicationMapping* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_applicationCodeRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_applicationCodeRegister() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_applicationCodeRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applicationCodeRegister(::grpc::ServerContext* context, const ::Application* request, ::ApplicationMapping* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestapplicationCodeRegister(::grpc::ServerContext* context, ::Application* request, ::grpc::ServerAsyncResponseWriter< ::ApplicationMapping>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_applicationCodeRegister<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_applicationCodeRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_applicationCodeRegister() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::Application, ::ApplicationMapping>(
          [this](::grpc::ServerContext* context,
                 const ::Application* request,
                 ::ApplicationMapping* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->applicationCodeRegister(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_applicationCodeRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applicationCodeRegister(::grpc::ServerContext* context, const ::Application* request, ::ApplicationMapping* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void applicationCodeRegister(::grpc::ServerContext* context, const ::Application* request, ::ApplicationMapping* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_applicationCodeRegister<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_applicationCodeRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_applicationCodeRegister() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_applicationCodeRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applicationCodeRegister(::grpc::ServerContext* context, const ::Application* request, ::ApplicationMapping* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_applicationCodeRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_applicationCodeRegister() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_applicationCodeRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applicationCodeRegister(::grpc::ServerContext* context, const ::Application* request, ::ApplicationMapping* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestapplicationCodeRegister(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_applicationCodeRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_applicationCodeRegister() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->applicationCodeRegister(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_applicationCodeRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status applicationCodeRegister(::grpc::ServerContext* context, const ::Application* request, ::ApplicationMapping* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void applicationCodeRegister(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_applicationCodeRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_applicationCodeRegister() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::Application, ::ApplicationMapping>(std::bind(&WithStreamedUnaryMethod_applicationCodeRegister<BaseClass>::StreamedapplicationCodeRegister, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_applicationCodeRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status applicationCodeRegister(::grpc::ServerContext* context, const ::Application* request, ::ApplicationMapping* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedapplicationCodeRegister(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Application,::ApplicationMapping>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_applicationCodeRegister<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_applicationCodeRegister<Service > StreamedService;
};


#endif  // GRPC_language_2dagent_2fApplicationRegisterService_2eproto__INCLUDED
