// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: language-agent/JVMMetricsService.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_language_2dagent_2fJVMMetricsService_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_language_2dagent_2fJVMMetricsService_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "language-agent/Downstream.pb.h"
#include "common/JVM.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_language_2dagent_2fJVMMetricsService_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_language_2dagent_2fJVMMetricsService_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_language_2dagent_2fJVMMetricsService_2eproto;
class JVMMetrics;
class JVMMetricsDefaultTypeInternal;
extern JVMMetricsDefaultTypeInternal _JVMMetrics_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::JVMMetrics* Arena::CreateMaybeMessage<::JVMMetrics>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class JVMMetrics :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:JVMMetrics) */ {
 public:
  JVMMetrics();
  virtual ~JVMMetrics();

  JVMMetrics(const JVMMetrics& from);
  JVMMetrics(JVMMetrics&& from) noexcept
    : JVMMetrics() {
    *this = ::std::move(from);
  }

  inline JVMMetrics& operator=(const JVMMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline JVMMetrics& operator=(JVMMetrics&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JVMMetrics& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JVMMetrics* internal_default_instance() {
    return reinterpret_cast<const JVMMetrics*>(
               &_JVMMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(JVMMetrics& a, JVMMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(JVMMetrics* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JVMMetrics* New() const final {
    return CreateMaybeMessage<JVMMetrics>(nullptr);
  }

  JVMMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JVMMetrics>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JVMMetrics& from);
  void MergeFrom(const JVMMetrics& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JVMMetrics* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "JVMMetrics";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_language_2dagent_2fJVMMetricsService_2eproto);
    return ::descriptor_table_language_2dagent_2fJVMMetricsService_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMetricsFieldNumber = 1,
    kApplicationInstanceIdFieldNumber = 2,
  };
  // repeated .JVMMetric metrics = 1;
  int metrics_size() const;
  private:
  int _internal_metrics_size() const;
  public:
  void clear_metrics();
  ::JVMMetric* mutable_metrics(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::JVMMetric >*
      mutable_metrics();
  private:
  const ::JVMMetric& _internal_metrics(int index) const;
  ::JVMMetric* _internal_add_metrics();
  public:
  const ::JVMMetric& metrics(int index) const;
  ::JVMMetric* add_metrics();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::JVMMetric >&
      metrics() const;

  // int32 applicationInstanceId = 2;
  void clear_applicationinstanceid();
  ::PROTOBUF_NAMESPACE_ID::int32 applicationinstanceid() const;
  void set_applicationinstanceid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_applicationinstanceid() const;
  void _internal_set_applicationinstanceid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:JVMMetrics)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::JVMMetric > metrics_;
  ::PROTOBUF_NAMESPACE_ID::int32 applicationinstanceid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_language_2dagent_2fJVMMetricsService_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JVMMetrics

// repeated .JVMMetric metrics = 1;
inline int JVMMetrics::_internal_metrics_size() const {
  return metrics_.size();
}
inline int JVMMetrics::metrics_size() const {
  return _internal_metrics_size();
}
inline ::JVMMetric* JVMMetrics::mutable_metrics(int index) {
  // @@protoc_insertion_point(field_mutable:JVMMetrics.metrics)
  return metrics_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::JVMMetric >*
JVMMetrics::mutable_metrics() {
  // @@protoc_insertion_point(field_mutable_list:JVMMetrics.metrics)
  return &metrics_;
}
inline const ::JVMMetric& JVMMetrics::_internal_metrics(int index) const {
  return metrics_.Get(index);
}
inline const ::JVMMetric& JVMMetrics::metrics(int index) const {
  // @@protoc_insertion_point(field_get:JVMMetrics.metrics)
  return _internal_metrics(index);
}
inline ::JVMMetric* JVMMetrics::_internal_add_metrics() {
  return metrics_.Add();
}
inline ::JVMMetric* JVMMetrics::add_metrics() {
  // @@protoc_insertion_point(field_add:JVMMetrics.metrics)
  return _internal_add_metrics();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::JVMMetric >&
JVMMetrics::metrics() const {
  // @@protoc_insertion_point(field_list:JVMMetrics.metrics)
  return metrics_;
}

// int32 applicationInstanceId = 2;
inline void JVMMetrics::clear_applicationinstanceid() {
  applicationinstanceid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 JVMMetrics::_internal_applicationinstanceid() const {
  return applicationinstanceid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 JVMMetrics::applicationinstanceid() const {
  // @@protoc_insertion_point(field_get:JVMMetrics.applicationInstanceId)
  return _internal_applicationinstanceid();
}
inline void JVMMetrics::_internal_set_applicationinstanceid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  applicationinstanceid_ = value;
}
inline void JVMMetrics::set_applicationinstanceid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_applicationinstanceid(value);
  // @@protoc_insertion_point(field_set:JVMMetrics.applicationInstanceId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_language_2dagent_2fJVMMetricsService_2eproto
