// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: language-agent/ApplicationRegisterService.proto

#include "language-agent/ApplicationRegisterService.pb.h"
#include "language-agent/ApplicationRegisterService.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* ApplicationRegisterService_method_names[] = {
  "/ApplicationRegisterService/applicationCodeRegister",
};

std::unique_ptr< ApplicationRegisterService::Stub> ApplicationRegisterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ApplicationRegisterService::Stub> stub(new ApplicationRegisterService::Stub(channel));
  return stub;
}

ApplicationRegisterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_applicationCodeRegister_(ApplicationRegisterService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ApplicationRegisterService::Stub::applicationCodeRegister(::grpc::ClientContext* context, const ::Application& request, ::ApplicationMapping* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_applicationCodeRegister_, context, request, response);
}

void ApplicationRegisterService::Stub::experimental_async::applicationCodeRegister(::grpc::ClientContext* context, const ::Application* request, ::ApplicationMapping* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_applicationCodeRegister_, context, request, response, std::move(f));
}

void ApplicationRegisterService::Stub::experimental_async::applicationCodeRegister(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ApplicationMapping* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_applicationCodeRegister_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::ApplicationMapping>* ApplicationRegisterService::Stub::AsyncapplicationCodeRegisterRaw(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ApplicationMapping>::Create(channel_.get(), cq, rpcmethod_applicationCodeRegister_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ApplicationMapping>* ApplicationRegisterService::Stub::PrepareAsyncapplicationCodeRegisterRaw(::grpc::ClientContext* context, const ::Application& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ApplicationMapping>::Create(channel_.get(), cq, rpcmethod_applicationCodeRegister_, context, request, false);
}

ApplicationRegisterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ApplicationRegisterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ApplicationRegisterService::Service, ::Application, ::ApplicationMapping>(
          std::mem_fn(&ApplicationRegisterService::Service::applicationCodeRegister), this)));
}

ApplicationRegisterService::Service::~Service() {
}

::grpc::Status ApplicationRegisterService::Service::applicationCodeRegister(::grpc::ServerContext* context, const ::Application* request, ::ApplicationMapping* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


