// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: register/InstancePing.proto
// Original file comments:
//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
#ifndef GRPC_register_2fInstancePing_2eproto__INCLUDED
#define GRPC_register_2fInstancePing_2eproto__INCLUDED

#include "register/InstancePing.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class ServiceInstancePing final {
 public:
  static constexpr char const* service_full_name() {
    return "ServiceInstancePing";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::Commands* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Commands>> AsyncdoPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Commands>>(AsyncdoPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Commands>> PrepareAsyncdoPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Commands>>(PrepareAsyncdoPingRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response, std::function<void(::grpc::Status)>) = 0;
      virtual void doPing(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Commands* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Commands>* AsyncdoPingRaw(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Commands>* PrepareAsyncdoPingRaw(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::Commands* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Commands>> AsyncdoPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Commands>>(AsyncdoPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Commands>> PrepareAsyncdoPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Commands>>(PrepareAsyncdoPingRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void doPing(::grpc::ClientContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response, std::function<void(::grpc::Status)>) override;
      void doPing(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Commands* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Commands>* AsyncdoPingRaw(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Commands>* PrepareAsyncdoPingRaw(::grpc::ClientContext* context, const ::ServiceInstancePingPkg& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_doPing_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status doPing(::grpc::ServerContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_doPing() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoPing(::grpc::ServerContext* context, ::ServiceInstancePingPkg* request, ::grpc::ServerAsyncResponseWriter< ::Commands>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_doPing<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_doPing() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::ServiceInstancePingPkg, ::Commands>(
          [this](::grpc::ServerContext* context,
                 const ::ServiceInstancePingPkg* request,
                 ::Commands* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->doPing(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void doPing(::grpc::ServerContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_doPing<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_doPing() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_doPing() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoPing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_doPing() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->doPing(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doPing(::grpc::ServerContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void doPing(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_doPing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_doPing() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::ServiceInstancePingPkg, ::Commands>(std::bind(&WithStreamedUnaryMethod_doPing<BaseClass>::StreameddoPing, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_doPing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status doPing(::grpc::ServerContext* context, const ::ServiceInstancePingPkg* request, ::Commands* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreameddoPing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ServiceInstancePingPkg,::Commands>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_doPing<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_doPing<Service > StreamedService;
};


#endif  // GRPC_register_2fInstancePing_2eproto__INCLUDED
