// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Demo.proto

#include "Demo.pb.h"
#include "Demo.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* TestRPC_method_names[] = {
  "/TestRPC/collect",
};

std::unique_ptr< TestRPC::Stub> TestRPC::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TestRPC::Stub> stub(new TestRPC::Stub(channel));
  return stub;
}

TestRPC::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_collect_(TestRPC_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TestRPC::Stub::collect(::grpc::ClientContext* context, const ::TestMessage& request, ::TestMessage* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_collect_, context, request, response);
}

void TestRPC::Stub::experimental_async::collect(::grpc::ClientContext* context, const ::TestMessage* request, ::TestMessage* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_collect_, context, request, response, std::move(f));
}

void TestRPC::Stub::experimental_async::collect(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TestMessage* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_collect_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::TestMessage>* TestRPC::Stub::AsynccollectRaw(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::TestMessage>::Create(channel_.get(), cq, rpcmethod_collect_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::TestMessage>* TestRPC::Stub::PrepareAsynccollectRaw(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::TestMessage>::Create(channel_.get(), cq, rpcmethod_collect_, context, request, false);
}

TestRPC::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TestRPC_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TestRPC::Service, ::TestMessage, ::TestMessage>(
          std::mem_fn(&TestRPC::Service::collect), this)));
}

TestRPC::Service::~Service() {
}

::grpc::Status TestRPC::Service::collect(::grpc::ServerContext* context, const ::TestMessage* request, ::TestMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


