// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Demo.proto
#ifndef GRPC_Demo_2eproto__INCLUDED
#define GRPC_Demo_2eproto__INCLUDED

#include "Demo.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class TestRPC final {
 public:
  static constexpr char const* service_full_name() {
    return "TestRPC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status collect(::grpc::ClientContext* context, const ::TestMessage& request, ::TestMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestMessage>> Asynccollect(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestMessage>>(AsynccollectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestMessage>> PrepareAsynccollect(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TestMessage>>(PrepareAsynccollectRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void collect(::grpc::ClientContext* context, const ::TestMessage* request, ::TestMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void collect(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TestMessage* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TestMessage>* AsynccollectRaw(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TestMessage>* PrepareAsynccollectRaw(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status collect(::grpc::ClientContext* context, const ::TestMessage& request, ::TestMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestMessage>> Asynccollect(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestMessage>>(AsynccollectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestMessage>> PrepareAsynccollect(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TestMessage>>(PrepareAsynccollectRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void collect(::grpc::ClientContext* context, const ::TestMessage* request, ::TestMessage* response, std::function<void(::grpc::Status)>) override;
      void collect(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TestMessage* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::TestMessage>* AsynccollectRaw(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TestMessage>* PrepareAsynccollectRaw(::grpc::ClientContext* context, const ::TestMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_collect_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status collect(::grpc::ServerContext* context, const ::TestMessage* request, ::TestMessage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_collect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_collect() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_collect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status collect(::grpc::ServerContext* context, const ::TestMessage* request, ::TestMessage* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcollect(::grpc::ServerContext* context, ::TestMessage* request, ::grpc::ServerAsyncResponseWriter< ::TestMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_collect<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_collect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_collect() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::TestMessage, ::TestMessage>(
          [this](::grpc::ServerContext* context,
                 const ::TestMessage* request,
                 ::TestMessage* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->collect(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_collect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status collect(::grpc::ServerContext* context, const ::TestMessage* request, ::TestMessage* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void collect(::grpc::ServerContext* context, const ::TestMessage* request, ::TestMessage* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_collect<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_collect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_collect() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_collect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status collect(::grpc::ServerContext* context, const ::TestMessage* request, ::TestMessage* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_collect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_collect() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_collect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status collect(::grpc::ServerContext* context, const ::TestMessage* request, ::TestMessage* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcollect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_collect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_collect() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->collect(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_collect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status collect(::grpc::ServerContext* context, const ::TestMessage* request, ::TestMessage* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void collect(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_collect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_collect() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::TestMessage, ::TestMessage>(std::bind(&WithStreamedUnaryMethod_collect<BaseClass>::Streamedcollect, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_collect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status collect(::grpc::ServerContext* context, const ::TestMessage* request, ::TestMessage* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedcollect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TestMessage,::TestMessage>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_collect<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_collect<Service > StreamedService;
};


#endif  // GRPC_Demo_2eproto__INCLUDED
